#ifndef __FLEX_RETURN_CODES_BRACKETED_STRINGS_H_
#define __FLEX_RETURN_CODES_BRACKETED_STRINGS_H_

#define	__END_CHUNK_ERROR  -1
#define	__END_OF_FILE  0
#define	__END_CHUNK  1
#define	__LEX_CORRECT  2
#define	__LEX_CORRECT_INSERT_RBRACK_RBRACK  3
#define	__ADD_SEMI  4
#define	__INSERT_DELIMITER  5
#define __INSERT_DELIMITER_ADD_SEMI 6
#define	__INSERT_COMMENT  7
#define	__INSERT_SINGLEMULTICOMMENT  8
#define	__INSERT_DELIMITER_BRACKETED_STRING  9
#define	__INSERT_STRING_WITH_BRACKETS  10
#define	__INSERT_STRING_MULTICOMMENT  11
#define	__END_CHUNK_INTERRUPTED_BRACKETED_STRING  12						
#define	__END_DOUBLE_LIST_STRING_RBRACK_RBRACK  13

#endif