#ifndef FLEX_RETURN_CODES_BRACKETED_STRINGS_H_
#define FLEX_RETURN_CODES_BRACKETED_STRINGS_H_

#define	END_CHUNK_ERROR  -1
#define	END_OF_FILE  0
#define	END_CHUNK  1
#define	LEX_CORRECT  2
#define	LEX_CORRECT_INSERT_RBRACK_RBRACK  3
#define	ADD_SEMI  4
#define	INSERT_DELIMITER  5
#define INSERT_DELIMITER_ADD_SEMI 6
#define	INSERT_COMMENT  7
#define	INSERT_SINGLEMULTICOMMENT  8
#define	INSERT_DELIMITER_BRACKETED_STRING  9
#define	INSERT_STRING_WITH_BRACKETS  10
#define	INSERT_STRING_MULTICOMMENT  11
#define	END_CHUNK_INTERRUPTED_BRACKETED_STRING  12						
#define	END_DOUBLE_LIST_STRING_RBRACK_RBRACK  13

#endif